#include "main.h"

/**
 * is_exit_is_env - checks if command is exit or env built-in
 * @arr: array of arguments generated by function split_string
 * @envp: environment passed down by main function
 * Description - Immediately follows the split_string function
 * and is invoked by the main function.
 * Return: 0 if successful, -1 if not, 1 if program to exit.
*/

int is_exit_is_env(char **arr, char **envp)
{
	int exit_value;

	if (_strcmp(arr[0], "exit") == 0)
	{
		printf("About to exit shell...");
		exit_value = exit_shell(arr);
		if (exit_value == 0)
			return (1);
	}
	else if (_strcmp(arr[0], "env") == 0)
	{
		if (arr[1] == NULL)
		{
			built_env(envp);
			return (0);
		}
		else
		{
			return (-1);
			perror("Usage: env");
		}
	}
	else
	{
		not_builtin_for_path(arr, envp);
	}
	return (0);
}

/**
 * built_env - an implemented version of the env command.
 * @env_t: environment, pointer to an array of strings
 * Description - a built-in implementation of env
 * Return: void
*/

void built_env(char **env_t)
{
	int i;
	int j;
	char *var;

	i = 0;

	while (env_t[i] != NULL)
	{
		j = 0;
		var = env_t[i];
		while (var[j] != '\0')
		{
			_putchar(var[j]);
			j++;
		}
		_putchar('\n');
		i++;
	}
}

/**
 * exit_shell - exits the shell
 * @arr: array of arguments
 * Definition - exits shell and includes code for exit status.
 * Return: integer; 0 if program to be exited, 1,if not
*/

int exit_shell(char **arr)
{
	int i;
	int count;
	char *status;
	int stat;

	i = 0;
	count = 0;

	while (arr[i] != NULL)
	{
		count++;
		i++;
	}
	if (count >= 2)
	{
		i = 0;
		status = arr[1];
		while (status[i] != '\0')
		{
			if (!(status[i] >= 48 && status[i] <= 57))
			{
				perror("Invalid argument");
			}
			i++;
		}
		stat = _atoi(status);
		/*free(arr);*/
		return (0);
		exit(stat);
	}
	else if (count == 1)
	{
		/*free(arr);*/
		return(0);
		exit(0);
	}
	return (1);
}
