#include "main.h"

/**
 * is_exit_is_env - checks if command is exit or env built-in
 * @arr: array of arguments generated by function split_string
 * @envp: environment passed down by main function
 * Description - comes immediately after split_string function.
 * called by the main function
 * Return: void
*/

void is_exit_is_env(char **arr, char **envp)
{
	if (_strcmp(arr[0], "exit") == 0)
	{
		printf("About to exit shell...");
		exit_shell(arr);
	}
	else if (_strcmp(arr[0], "env") == 0)
	{
		if (arr[1] == NULL)
			built_env(envp);
		else
			perror("Usage: env");
	}
	else
	{
		not_builtin_for_path(arr, envp);
	}
}

/**
 * built_env - an implemented version of the env command.
 * @env_t: environment, pointer to an array of strings
 * Description - a built-in implementation of env
 * Return: void
*/

void built_env(char **env_t)
{
	int i;
	int j;
	char *var;

	i = 0;

	while (env_t[i] != NULL)
	{
		j = 0;
		var = env_t[i];
		while (var[j] != '\0')
		{
			_putchar(var[j]);
			j++;
		}
		_putchar('\n');
		i++;
	}
}

/**
 * exit_shell - exits the shell
 * @arr: array of arguments
 * Definition - exits shell and includes code for exit status.
 * Return: void
*/

void exit_shell(char **arr)
{
	int i;
	int count;
	char *status;
	int stat;

	i = 0;
	count = 0;

	while (arr[i] != NULL)
	{
		count++;
		i++;
	}
	if (count >= 2)
	{
		i = 0;
		status = arr[1];
		while (status[i] != '\0')
		{
			if (!(status[i] >= 48 && status[i] <= 57))
				perror("Invalid argument");
			i++;
		}
		stat = _atoi(status);
		exit(stat);
	}
	else if (count == 1)
		exit(0);

}
